version: '3.8'

services:
  bank_service:
    build: ./
    ports:
    - 0.0.0.0:8000:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=bankDB
    ports:
      - 5432:5432 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bankDB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
