global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_server'
    static_configs:
      - targets: ['auth:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
